------------------------
-- HTML用のテーブル定義
------------------------
-- DROP
DROP TABLE HTML_MAIL_ALT_TEXT_TEMPLATE CASCADE CONSTRAINTS;
DROP TABLE HTML_MAIL_ALT_TEXT CASCADE CONSTRAINTS;

-- CREATE
---- メール要求の関連テーブル
CREATE TABLE HTML_MAIL_ALT_TEXT
(
    MAIL_REQUEST_ID                NVARCHAR2(20) NOT NULL,
    ALTERNATIVE_TEXT               NCLOB NOT NULL
)
;
ALTER TABLE HTML_MAIL_ALT_TEXT
    ADD(PRIMARY KEY (MAIL_REQUEST_ID) USING INDEX)
;
---- メールテンプレート
CREATE TABLE HTML_MAIL_ALT_TEXT_TEMPLATE
(
    MAIL_TEMPLATE_ID               NVARCHAR2(10) NOT NULL,
    LANG                           CHAR(2) NOT NULL,
    ALTERNATIVE_TEXT               NCLOB NOT NULL
)
;
ALTER TABLE HTML_MAIL_ALT_TEXT_TEMPLATE
    ADD(PRIMARY KEY (MAIL_TEMPLATE_ID, LANG) USING INDEX)
;


-- テスト実行時の環境SET_UP
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
CREATE TABLE MESSAGE
(
    MESSAGE_ID                     CHAR(10) NOT NULL,
    LANG                           CHAR(2) NOT NULL,
    MESSAGE                        NVARCHAR2(200) NOT NULL
)
;
ALTER TABLE MESSAGE
    ADD(PRIMARY KEY (MESSAGE_ID, LANG) USING INDEX)
;

DROP TABLE MAIL_REQUEST CASCADE CONSTRAINTS;
CREATE TABLE MAIL_REQUEST
(
    MAIL_REQUEST_ID                NVARCHAR2(20) NOT NULL,
    SUBJECT                        NVARCHAR2(150) NOT NULL,
    MAIL_FROM                      NVARCHAR2(100) NOT NULL,
    REPLY_TO                       NVARCHAR2(100) NOT NULL,
    RETURN_PATH                    NVARCHAR2(100) NOT NULL,
    CHARSET                        NVARCHAR2(50) NOT NULL,
    STATUS                         CHAR(1) NOT NULL,
    REQUEST_DATETIME               TIMESTAMP NOT NULL,
    SEND_DATETIME                  TIMESTAMP,
    MAIL_BODY                      NCLOB NOT NULL
)
;
ALTER TABLE MAIL_REQUEST
    ADD(PRIMARY KEY (MAIL_REQUEST_ID) USING INDEX)
;
DROP TABLE MAIL_ATTACHED_FILE CASCADE CONSTRAINTS;
CREATE TABLE MAIL_ATTACHED_FILE
(
    MAIL_REQUEST_ID                NVARCHAR2(20) NOT NULL,
    SERIAL_NUMBER                  NUMBER(10,0) NOT NULL,
    FILE_NAME                      NVARCHAR2(150) NOT NULL,
    CONTENT_TYPE                   NVARCHAR2(50) NOT NULL,
    ATTACHED_FILE                  BLOB NOT NULL
)
;
ALTER TABLE MAIL_ATTACHED_FILE
    ADD(PRIMARY KEY (MAIL_REQUEST_ID, SERIAL_NUMBER) USING INDEX)
;
DROP TABLE MAIL_RECIPIENT CASCADE CONSTRAINTS;
CREATE TABLE MAIL_RECIPIENT
(
    MAIL_REQUEST_ID                NVARCHAR2(20) NOT NULL,
    SERIAL_NUMBER                  NUMBER(10,0) NOT NULL,
    RECIPIENT_TYPE                 CHAR(1) NOT NULL,
    MAIL_ADDRESS                   NVARCHAR2(100) NOT NULL
)
;
ALTER TABLE MAIL_RECIPIENT
    ADD(PRIMARY KEY (MAIL_REQUEST_ID, SERIAL_NUMBER) USING INDEX)
;
DROP TABLE MAIL_TEMPLATE CASCADE CONSTRAINTS;
CREATE TABLE MAIL_TEMPLATE
(
    MAIL_TEMPLATE_ID               NVARCHAR2(10) NOT NULL,
    LANG                           CHAR(2) NOT NULL,
    SUBJECT                        NVARCHAR2(150) NOT NULL,
    CHARSET                        NVARCHAR2(50) NOT NULL,
    MAIL_BODY                      CLOB NOT NULL
)
;
ALTER TABLE MAIL_TEMPLATE
    ADD(PRIMARY KEY (MAIL_TEMPLATE_ID, LANG) USING INDEX)
;

DROP TABLE ID_GENERATE_MAIL CASCADE CONSTRAINTS;
CREATE TABLE ID_GENERATE_MAIL
(
    ID                             CHAR(2) NOT NULL,
    NO                             NUMBER(10,0) NOT NULL
)
;
ALTER TABLE ID_GENERATE_MAIL
    ADD(PRIMARY KEY (ID) USING INDEX)
;
DROP TABLE BATCH_REQUEST CASCADE CONSTRAINTS;
CREATE TABLE BATCH_REQUEST
(
    REQUEST_ID                      CHAR(10) NOT NULL,
    REQUEST_NAME                    NVARCHAR2(100) NOT NULL,
    PROCESS_HALT_FLG                CHAR(1) NOT NULL,
    PROCESS_ACTIVE_FLG              CHAR(1) NOT NULL,
    SERVICE_AVAILABLE               CHAR(1) NOT NULL
)
;
