version: "3.4"
services:
  mock-server:
    image: "mockoon/cli:3.0.0"
    ports:
      - "3000:3000"
    volumes:
      - ./data.json:/data:readonly
    command: ["--data", "data", "--port", "3000"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/your-healthcheck-route || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 10s
