CREATE TABLE CODE_NAME (
  CODE_ID CHAR(8 CHAR) NOT NULL ,
  CODE_VALUE VARCHAR2(2 CHAR) NOT NULL ,
  LANG CHAR(2 CHAR) NOT NULL ,
  SORT_ORDER NUMBER(2) NOT NULL ,
  CODE_NAME VARCHAR2(50 CHAR) NOT NULL ,
  SHORT_NAME VARCHAR2(50 CHAR),
  OPTION01 VARCHAR2(50 CHAR),
  OPTION02 VARCHAR2(50 CHAR),
  OPTION03 VARCHAR2(50 CHAR),
  OPTION04 VARCHAR2(50 CHAR),
  OPTION05 VARCHAR2(50 CHAR),
  OPTION06 VARCHAR2(50 CHAR),
  OPTION07 VARCHAR2(50 CHAR),
  OPTION08 VARCHAR2(50 CHAR),
  OPTION09 VARCHAR2(50 CHAR),
  OPTION10 VARCHAR2(50 CHAR)
);
COMMENT ON table CODE_NAME is '�R�[�h����';
COMMENT ON column CODE_NAME.CODE_ID is '�R�[�hID';
COMMENT ON column CODE_NAME.CODE_VALUE is '�R�[�h�l';
COMMENT ON column CODE_NAME.LANG is '����';
COMMENT ON column CODE_NAME.SORT_ORDER is '�\�[�g��';
COMMENT ON column CODE_NAME.CODE_NAME is '����';
COMMENT ON column CODE_NAME.SHORT_NAME is '�R�[�h����';
COMMENT ON column CODE_NAME.OPTION01 is '�I�v�V��������01';
COMMENT ON column CODE_NAME.OPTION02 is '�I�v�V��������02';
COMMENT ON column CODE_NAME.OPTION03 is '�I�v�V��������03';
COMMENT ON column CODE_NAME.OPTION04 is '�I�v�V��������04';
COMMENT ON column CODE_NAME.OPTION05 is '�I�v�V��������05';
COMMENT ON column CODE_NAME.OPTION06 is '�I�v�V��������06';
COMMENT ON column CODE_NAME.OPTION07 is '�I�v�V��������07';
COMMENT ON column CODE_NAME.OPTION08 is '�I�v�V��������08';
COMMENT ON column CODE_NAME.OPTION09 is '�I�v�V��������09';
COMMENT ON column CODE_NAME.OPTION10 is '�I�v�V��������10';
CREATE TABLE CODE_PATTERN (
  CODE_ID CHAR(8 CHAR) NOT NULL ,
  CODE_VALUE VARCHAR2(2 CHAR) NOT NULL ,
  PATTERN01 CHAR(1 CHAR) NOT NULL ,
  PATTERN02 CHAR(1 CHAR),
  PATTERN03 CHAR(1 CHAR),
  PATTERN04 CHAR(1 CHAR),
  PATTERN05 CHAR(1 CHAR),
  PATTERN06 CHAR(1 CHAR),
  PATTERN07 CHAR(1 CHAR),
  PATTERN08 CHAR(1 CHAR),
  PATTERN09 CHAR(1 CHAR),
  PATTERN10 CHAR(1 CHAR),
  PATTERN11 CHAR(1 CHAR),
  PATTERN12 CHAR(1 CHAR),
  PATTERN13 CHAR(1 CHAR),
  PATTERN14 CHAR(1 CHAR),
  PATTERN15 CHAR(1 CHAR),
  PATTERN16 CHAR(1 CHAR),
  PATTERN17 CHAR(1 CHAR),
  PATTERN18 CHAR(1 CHAR),
  PATTERN19 CHAR(1 CHAR),
  PATTERN20 CHAR(1 CHAR)
);
COMMENT ON table CODE_PATTERN is '�R�[�h�p�^�[��';
COMMENT ON column CODE_PATTERN.CODE_ID is '�R�[�hID';
COMMENT ON column CODE_PATTERN.CODE_VALUE is '�R�[�h�l';
COMMENT ON column CODE_PATTERN.PATTERN01 is '�p�^�[��01';
COMMENT ON column CODE_PATTERN.PATTERN02 is '�p�^�[��02';
COMMENT ON column CODE_PATTERN.PATTERN03 is '�p�^�[��03';
COMMENT ON column CODE_PATTERN.PATTERN04 is '�p�^�[��04';
COMMENT ON column CODE_PATTERN.PATTERN05 is '�p�^�[��05';
COMMENT ON column CODE_PATTERN.PATTERN06 is '�p�^�[��06';
COMMENT ON column CODE_PATTERN.PATTERN07 is '�p�^�[��07';
COMMENT ON column CODE_PATTERN.PATTERN08 is '�p�^�[��08';
COMMENT ON column CODE_PATTERN.PATTERN09 is '�p�^�[��09';
COMMENT ON column CODE_PATTERN.PATTERN10 is '�p�^�[��10';
COMMENT ON column CODE_PATTERN.PATTERN11 is '�p�^�[��11';
COMMENT ON column CODE_PATTERN.PATTERN12 is '�p�^�[��12';
COMMENT ON column CODE_PATTERN.PATTERN13 is '�p�^�[��13';
COMMENT ON column CODE_PATTERN.PATTERN14 is '�p�^�[��14';
COMMENT ON column CODE_PATTERN.PATTERN15 is '�p�^�[��15';
COMMENT ON column CODE_PATTERN.PATTERN16 is '�p�^�[��16';
COMMENT ON column CODE_PATTERN.PATTERN17 is '�p�^�[��17';
COMMENT ON column CODE_PATTERN.PATTERN18 is '�p�^�[��18';
COMMENT ON column CODE_PATTERN.PATTERN19 is '�p�^�[��19';
COMMENT ON column CODE_PATTERN.PATTERN20 is '�p�^�[��20';
CREATE TABLE USER_SESSION (
  SESSION_ID VARCHAR2(100 CHAR) NOT NULL ,
  SESSION_OBJECT BLOB,
  EXPIRATION_DATETIME TIMESTAMP NOT NULL 
);
COMMENT ON table USER_SESSION is '���[�U�Z�b�V����';
COMMENT ON column USER_SESSION.SESSION_ID is '�Z�b�V����ID';
COMMENT ON column USER_SESSION.SESSION_OBJECT is '�Z�b�V�����I�u�W�F�N�g';
COMMENT ON column USER_SESSION.EXPIRATION_DATETIME is '�L������';
ALTER TABLE USER_SESSION
ADD CONSTRAINT PK_USER_SESSION PRIMARY KEY
(
  SESSION_ID
);
ALTER TABLE CODE_PATTERN
ADD CONSTRAINT SYS_C0058550 PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE
);
ALTER TABLE CODE_NAME
ADD CONSTRAINT SYS_C0058560 PRIMARY KEY
(
  CODE_ID,
  CODE_VALUE,
  LANG
);
ALTER TABLE CODE_NAME
ADD 
FOREIGN KEY (
  CODE_ID,
  CODE_VALUE
) REFERENCES CODE_PATTERN (
  CODE_ID,
  CODE_VALUE
);